// data.js
export const data = {
  skills: {
    programming: [
      "Python",
      "Java",
      "C/C++",
      "JavaScript",
      "HTML",
      "CSS",
      "SQL",
      "GLSL",
    ],
    ai: [
      "NumPy",
      "Pandas",
      "OpenCV",
      "PyTorch",
      "Tensorflow",
      "Scikit-learn",
      "LangChain",
      "GANs",
      "Computer Vision",
      "Audio Processing",
      "NLP",
      "LLM",
      "RAG",
      "Gen AI",
      "Resemblyzer",
      "AutoVC",
      "U-net",
      "ResNet",
      "Probabilistic Machine Learning",
      "Relational Database",
      "Vector Database",
    ],
    web: [
      "Node",
      "Express",
      "jQuery",
      "Bootstrap",
      "MongoDB",
      "Three.js",
      "Django",
      "JSP",
      "Servlets",
    ],
    tools: ["Azure", "Git", "Linux", "Power BI", "Excel", "Power BI"],
  },
  languages: ["English", "Thai", "German", "Mandarin"],
  experience: [
    {
      company: "KPMG",
      role: "Data Scientist - Technology Consulting",
      date: "Jun 2024 - Aug 2024",
      points: [
        "Designed and created an agentic AI incorporating adaptive RAG, corrective RAG, and self-RAG together, which outperformed all other traditional models while also preventing LLM’s hallucination.",
        "Invented audit AI to automate the entire audit’s workflow using RAG and LLM, which can automatically extract and semantically analyze information on a financial statement. This AI reduces auditing time from weeks to seconds.",
        "With advanced OCR utilizing computer vision technology (e.g., YOLO, etc.), this audit AI tolerates both structured and unstructured (e.g., .pdf, .jpg, etc.) input financial statements and other relevant documents.",
        "The audit AI provides the service by utilizing a vector database (i.e., Pinecone), Microsoft Azure, and LangChain.",
        "Analyzed Cognitive Contract Management (CCM) system to find market feasibility and ways to develop solutions for customers.",
      ],
      tools: [
        "Python",
        "LangChain",
        "LLM",
        "RAG",
        "Vector Database",
        "Agentic Model",
        "NLP",
        "Computer Vision",
        "Azure",
        "MLOPs",
      ],
    },

    {
      company: "Saint Francis University",
      role: "Deep Learning Research Assistant",
      date: "Jun 2023 - July 2023",
      points: [
        "Analyzed and improved deepfake pipeline, including image generation using Generative Adversarial Networks (GANs), facial alignment using Face Alignment Network (FAN), audio disentanglement using AutoVC and Resemblyzer, landmark displacement using Deep Neural Network (DNN), and image2image translation.",
        "Collaborated with the researcher team to fix bugs and make the code stable on the more updated OS (Linux & Windows).",
        "Created GUI and tutorial for the team, helping reduce the time for further implementation by more than 50%.",
      ],
      tools: [
        "Python",
        "PyTorch",
        "Deep Learning",
        "GUI",
        "Generative Adversarial Networks",
        "Linux",
      ],
    },

    {
      company: "GoPark",
      role: "Co-founder & AI/ML Engineer",
      date: "Jun 2023 - Present",
      points: [
        "Built machine learning models (e.g., RNN, LSTM, etc.) to handle long-term dependencies in predicting parking lot vacancies. Help GoPark’s customers know where to park 30 times faster and reduce traffic congestion.",
        "Created a database for managing parking lots in real time, an algorithm to reserve parking spots, and payment method for the reservation while generating verification QR code in one go.",
        "Showcased and awarded funding in hackathons: PolyHack, PolyU Proof of Concept, and Microsoft Imagine Cup.",
      ],
      tools: [
        "Python",
        "SQL",
        "JavaScript",
        "HTML",
        "CSS",
        "PyTorch",
        "Django",
        "Payment Gateway (Stripe)",
      ],
    },

    {
      company: "StarkWare",
      role: "StarkNet House Research Fellow & Finalist",
      date: "Jun 2022 - Sep 2022",
      points: [
        'Research on the topic "STARK: A Proof System Unlocking Blockchain Scalability"',
        'Published "For Dummies" paper, adhered MIT open-source license, to make a shortcut for people who want to start programming in Cairo on StarkNet, the L2 network implemented on top of Ethereum.',
        "Be the grab-and-go reference about what ZK-STARK does to achieve scalability, which is a required fundamental understanding to develop smart contracts and dApps on StarkNet.",
      ],
      tools: ["Cairo", "StarkNet", "Blockchain", "Cryptography"],
    },
    // Add other experiences similarly
  ],
  education: [
    {
      institution: "The Hong Kong Polytechnic University",
      degree: "BSc (Hons) Artificial Intelligence & Information Engineering",
      date: "Aug 2022 - Present",
      gpa: "3.96",
      achievements: [
        "All A+ in Deep learning & Deep Neural Networks, Calculus and Probability & Statistics, Foundations of Data Science, Fundamental AI & Data Analytics, Computer Programming, Foundation Techniques in Artificial Intelligence",
        "Dean’s Honors List 2022/23",
      ],
    },
    // Add other education entries
  ],
  achievements: [
    "JP Morgan Code for Good: Qualified for the final round and finished as one of the top 4 teams in Hong Kong",
    "Hong Kong Techathon 2024: Merit Award (Open Group under The Category of Digital Economy)",
    "Cathay Pacific Hackathon: Qualified for the semi-final round",
    "Dr. Winnie S M Tang-PolyU Student Innovation & Entrepreneurship Scholarship for Supporting GoPark",
    "PolyHack 2023: Third Place Award, Best GIS Award, Most Innovative Award, HK$ 100,000 Funding",
    "Wong Tit-shing Student Exchange Scholarship funding Exchange Semester in The University of Manchester, UK",
    "The Hong Kong Polytechnic University Entry Scholarship covering tuition fee and living expenses until completing bachelor's degree",
    "International Blockchain Olympiad (IBCOL): First place in the country and selected as the nation's representative",
    "National Physics Olympiad: Top regional 6",
    "National Science and Technology Development Agency's long-term scholarship supports education until completing a doctoral degree",
  ],
};
